[package]
name = "bf-on-browsers"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
futures = "0.3"
js-sys = "0.3.32"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4.5"
